name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Kumuha ng latest code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run build
      - name: Start or Restart sa Port 6000
        run: |
          if pm2 describe crypto-ai-forecast-claude > /dev/null; then
            echo "App is running, restarting..."
            pm2 restart crypto-ai-forecast-claude
          else
            echo "First time deployment!"
            pm2 serve dist 6000 --name "crypto-ai-forecast-claude" --spa
          fi
