name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Kumuha ng latest code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run build

      - name: Start or Restart sa Port 6000
        run: |
          pm2 describe crypto-ai-forecast-claude > /dev/null
          if [ $? -eq 0 ]; then
            PORT=6000 pm2 restart crypto-ai-forecast-claude
          else
            PORT=6000 pm2 start npm --name "crypto-ai-forecast-claude" -- start
          fi
